import type { DashboardConfig } from "../types/dashboard";

export const defaultDashboard: DashboardConfig = {
  id: "main",
  title: "System Overview",
  panels: [
    {
      id: "total-events",
      title: "Total Events (24h)",
      spl: "search index=_internal | stats count",
      vizType: "kpi",
      earliest: "-24h",
      latest: "now",
      refreshInterval: 60,
      span: 1,
      height: "sm",
      chartOptions: { categories: ["count"] },
    },
    {
      id: "error-count",
      title: "Errors (1h)",
      spl: 'search index=_internal log_level=ERROR | stats count',
      vizType: "kpi",
      earliest: "-1h",
      latest: "now",
      refreshInterval: 30,
      span: 1,
      height: "sm",
      chartOptions: { categories: ["count"] },
    },
    {
      id: "warn-count",
      title: "Warnings (1h)",
      spl: 'search index=_internal log_level=WARN | stats count',
      vizType: "kpi",
      earliest: "-1h",
      latest: "now",
      refreshInterval: 30,
      span: 1,
      height: "sm",
      chartOptions: { categories: ["count"] },
    },
    {
      id: "sources",
      title: "Top Sources",
      spl: "search index=_internal | top limit=5 source",
      vizType: "kpi",
      earliest: "-1h",
      latest: "now",
      refreshInterval: 60,
      span: 1,
      height: "sm",
      chartOptions: { categories: ["count"] },
    },
    {
      id: "events-over-time",
      title: "Events Over Time",
      spl: "search index=_internal | timechart span=5m count",
      vizType: "line",
      earliest: "-1h",
      latest: "now",
      refreshInterval: 30,
      span: 3,
      height: "md",
    },
    {
      id: "log-levels",
      title: "Log Levels",
      spl: "search index=_internal | timechart span=5m count by log_level",
      vizType: "bar",
      earliest: "-1h",
      latest: "now",
      refreshInterval: 30,
      span: 1,
      height: "md",
    },
    {
      id: "recent-events",
      title: "Recent Events",
      spl: "search index=_internal | head 20 | table _time source log_level message",
      vizType: "table",
      earliest: "-15m",
      latest: "now",
      refreshInterval: 15,
      span: 4,
      height: "lg",
    },
  ],
};
